### ISSUE TITLE
[Feature Request] Easily modify word lists

### ISSUE THREAD

**Issue by vatterspun** [m8urnett/pafwert#2]
One thing I was worried about when I tested this program initially was whether or not it was actually using random words or if it was selecting from a group that it's author found humorous.  You have a very well-written help file that addresses this very clearly, but as any group selection is predictable, maybe add the ability to add additional terms/lists/etc. without a registry edit?

**Comment by m8urnett** [comment]
You can edit any of the text files in the wordlist directory as well as the patterns in patterns.cfg.

**Comment by vatterspun** [comment]
Oh.  Yeah that works.
